import { Button, Grid } from '@material-ui/core'
import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/Layout/Layout'
import { useAuth } from '../contexts/AuthContext'


export default function Home() {
  const { currentUser } = useAuth()

  return (
    <Layout>

      <Head>
        <title>now shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container justify="space-around">
        {!currentUser && (
          <>
            <Button>
              <Link href="/login">
                <a>Already have an account? Log in</a>
              </Link>
            </Button>
            <br />
            <Button>
              <Link href="/signup">
                <a>Don't have an account? Sign Up</a>
              </Link>
            </Button>
          </>
        )}
      </Grid>
    </Layout>
  )
}
